pipeline:
  release:
    image: registry.usw.co/uswitch/clojure
    secrets: [ CLOJARS_USERNAME, CLOJARS_PASSWORD ]
    when:
      branch: master
      event: push
    commands:
      - lein deps
      - lein codox
      - lein jar
      - lein deploy clojars

  build-gh-pages:
    image: registry.usw.co/uswitch/clojure
    when:
      branch: master
      event: push
    commands:
      - lein codox
      - mkdir .docs && mv target/doc/* .docs/
      - rm -r * && rm .gitignore && rm .drone.yml
      - mv .docs/* . && rmdir .docs

  commit-gh-pages:
    image: plugins/git
    when:
      branch: master
      event: push
    commands:
      - git config user.name dodgydrone
      - git config user.email drone@drone.drone
      - git checkout --orphan gh-pages
      - git add .
      - git commit -m "dox"

   git_push:
     image: appleboy/drone-git-push
     remote_name: origin
     branch: gh-pages
     local_ref: gh-pages
