pipeline:
  build-uberjar:
    image: registry.usw.co/uswitch/clojure
    commands:
      - lein deps
      - lein test
      - lein jar

  release:
    image: registry.usw.co/uswitch/clojure
    when:
      branch: master
      event: push
    commands:
      - lein deps
      - lein jar
      - lein deploy releases

  notify-slack:
    when:
      branch: master
      status: [ success, failure ]
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: comparison-api
    username: drone
    template: >
      {{ repo.name }}:{{ build.branch }} finished build {{ build.number }}
      with a status of {{ build.status }}. See it at https://ci.usw.co/uswitch/{{ repo.name }}/{{ build.number }}
